
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.23.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Tiny4X.UI.MainMenu
{
    using System;
    using Terminal.Gui;


    public partial class MainMenu : Terminal.Gui.Window
    {

        private Terminal.Gui.ColorScheme greyOnBlack;

        private Terminal.Gui.Button btnJoin;

        private Terminal.Gui.Button btnHost;

        private Terminal.Gui.Button btnEdit;

        private Terminal.Gui.Button btnExit;

        private void InitializeComponent()
        {
            this.btnExit = new Terminal.Gui.Button();
            this.btnEdit = new Terminal.Gui.Button();
            this.btnHost = new Terminal.Gui.Button();
            this.btnJoin = new Terminal.Gui.Button();
            this.greyOnBlack = new Terminal.Gui.ColorScheme();
            this.greyOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.ColorScheme = this.greyOnBlack;
            this.Modal = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Double;
            this.Border.BorderBrush = Terminal.Gui.Color.Blue;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.Title = "Tiny4X!";
            this.btnJoin.Width = 13;
            this.btnJoin.Height = 1;
            this.btnJoin.X = Pos.Center();
            this.btnJoin.Y = Pos.Top(btnHost) - 2;
            this.btnJoin.Data = "btnJoin";
            this.btnJoin.Text = "Join Game";
            this.btnJoin.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnJoin.IsDefault = false;
            this.Add(this.btnJoin);
            this.btnHost.Width = 13;
            this.btnHost.Height = 1;
            this.btnHost.X = Pos.Center();
            this.btnHost.Y = Pos.Center() - 1;
            this.btnHost.Data = "btnHost";
            this.btnHost.Text = "Host Game";
            this.btnHost.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnHost.IsDefault = false;
            this.Add(this.btnHost);
            this.btnEdit.Width = 13;
            this.btnEdit.Height = 1;
            this.btnEdit.X = Pos.Center();
            this.btnEdit.Y = Pos.Bottom(btnHost) + 1;
            this.btnEdit.Data = "btnEdit";
            this.btnEdit.Text = "Edit Deck";
            this.btnEdit.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnEdit.IsDefault = false;
            this.Add(this.btnEdit);
            this.btnExit.Width = 13;
            this.btnExit.Height = 1;
            this.btnExit.X = Pos.Center();
            this.btnExit.Y = Pos.Bottom(btnEdit) + 1;
            this.btnExit.Data = "btnExit";
            this.btnExit.Text = "Exit Game";
            this.btnExit.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnExit.IsDefault = false;
            this.Add(this.btnExit);
        }
    }
}
