using Terminal.Gui;
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.23.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Tiny4X.UI.MainMenu
{

    public partial class MainMenu
    {
        public MainMenu()
        {
            InitializeComponent();

            btnEdit.Clicked += () => Application.Run<DeckEditor>();
            btnExit.Clicked += () => Application.RequestStop();
        }
    }
}
