
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.23.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Tiny4X.UI
{
    using Terminal.Gui;


    public partial class DeckEditor
    {

        public DeckEditor()
        {
            InitializeComponent();
            deckView.Title = "Decks";
            cardView.Title = "Cards";
            descView.Title = "Description";
        }
    }
}
