
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.23.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Tiny4X.UI
{
    using System;
    using Terminal.Gui;


    public partial class DeckEditor : Terminal.Gui.Window
    {

        private Terminal.Gui.ColorScheme greyOnBlack;

        private Terminal.Gui.FrameView deckView;

        private Terminal.Gui.TreeView treeView;

        private Terminal.Gui.FrameView cardView;

        private Terminal.Gui.Label search;

        private Terminal.Gui.TextField textField;

        private Terminal.Gui.ListView listView;

        private Terminal.Gui.FrameView descView;

        private Terminal.Gui.TextView textView;

        private void InitializeComponent()
        {
            this.textView = new Terminal.Gui.TextView();
            this.descView = new Terminal.Gui.FrameView();
            this.listView = new Terminal.Gui.ListView();
            this.textField = new Terminal.Gui.TextField();
            this.search = new Terminal.Gui.Label();
            this.cardView = new Terminal.Gui.FrameView();
            this.treeView = new Terminal.Gui.TreeView();
            this.deckView = new Terminal.Gui.FrameView();
            this.greyOnBlack = new Terminal.Gui.ColorScheme();
            this.greyOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.Blue;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.deckView.Width = 28;
            this.deckView.Height = 28;
            this.deckView.X = 0;
            this.deckView.Y = 0;
            this.deckView.Data = "deckView";
            this.deckView.Border.BorderStyle = Terminal.Gui.BorderStyle.Double;
            this.deckView.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.deckView.Border.Effect3D = false;
            this.deckView.Border.Effect3DBrush = null;
            this.deckView.Border.DrawMarginFrame = true;
            this.deckView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.deckView.Title = "Heya";
            this.Add(this.deckView);
            this.treeView.Width = 26;
            this.treeView.Height = 28;
            this.treeView.X = 0;
            this.treeView.Y = 0;
            this.treeView.Data = "treeView";
            this.treeView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.treeView.Style.CollapseableSymbol = '-';
            this.treeView.Style.ColorExpandSymbol = false;
            this.treeView.Style.ExpandableSymbol = '+';
            this.treeView.Style.InvertExpandSymbolColors = false;
            this.treeView.Style.LeaveLastRow = false;
            this.treeView.Style.ShowBranchLines = true;
            this.deckView.Add(this.treeView);
            this.cardView.Width = 24;
            this.cardView.Height = 28;
            this.cardView.X = 28;
            this.cardView.Y = 0;
            this.cardView.Data = "cardView";
            this.cardView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.cardView.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.cardView.Border.Effect3D = false;
            this.cardView.Border.Effect3DBrush = null;
            this.cardView.Border.DrawMarginFrame = true;
            this.cardView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.cardView.Title = "Heya";
            this.Add(this.cardView);
            this.search.Width = 4;
            this.search.Height = 1;
            this.search.X = 0;
            this.search.Y = 0;
            this.search.Data = "search";
            this.search.Text = "Heya";
            this.search.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.cardView.Add(this.search);
            this.textField.Width = 17;
            this.textField.Height = 2;
            this.textField.X = 5;
            this.textField.Y = 0;
            this.textField.Secret = false;
            this.textField.Data = "textField";
            this.textField.Text = "";
            this.textField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.cardView.Add(this.textField);
            this.listView.Width = 22;
            this.listView.Height = 26;
            this.listView.X = 0;
            this.listView.Y = 1;
            this.listView.Data = "listView";
            this.listView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.listView.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Item1",
                        "Item2",
                        "Item3"});
            this.cardView.Add(this.listView);
            this.descView.Width = 66;
            this.descView.Height = 28;
            this.descView.X = 52;
            this.descView.Y = 0;
            this.descView.Data = "descView";
            this.descView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.descView.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.descView.Border.Effect3D = false;
            this.descView.Border.Effect3DBrush = null;
            this.descView.Border.DrawMarginFrame = true;
            this.descView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.descView.Title = "Heya";
            this.Add(this.descView);
            this.textView.Width = 62;
            this.textView.Height = 26;
            this.textView.X = 1;
            this.textView.Y = 0;
            this.textView.AllowsTab = true;
            this.textView.AllowsReturn = true;
            this.textView.WordWrap = false;
            this.textView.Data = "textView";
            this.textView.Text = "Description";
            this.textView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.descView.Add(this.textView);
        }
    }
}
