
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.23.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Tiny4X.UI.GameStage {
    using System;
    using Terminal.Gui;
    
    
    public partial class GameStage : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme tgDefault;
        
        private Terminal.Gui.ColorScheme greyOnBlack;
        
        private Terminal.Gui.FrameView mapView;
        
        private Terminal.Gui.TableView tableView;
        
        private Terminal.Gui.TabView tabView;
        
        private Terminal.Gui.FrameView frameView;
        
        private Terminal.Gui.FrameView frameView2;
        
        private void InitializeComponent() {
            this.frameView2 = new Terminal.Gui.FrameView();
            this.frameView = new Terminal.Gui.FrameView();
            this.tabView = new Terminal.Gui.TabView();
            this.tableView = new Terminal.Gui.TableView();
            this.mapView = new Terminal.Gui.FrameView();
            this.tgDefault = new Terminal.Gui.ColorScheme();
            this.tgDefault.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.tgDefault.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightCyan, Terminal.Gui.Color.Blue);
            this.tgDefault.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.tgDefault.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Gray);
            this.tgDefault.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Brown, Terminal.Gui.Color.Blue);
            this.greyOnBlack = new Terminal.Gui.ColorScheme();
            this.greyOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.ColorScheme = this.greyOnBlack;
            this.Modal = true;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Double;
            this.Border.BorderBrush = Terminal.Gui.Color.Blue;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Tiny4X!";
            this.mapView.Width = Dim.Percent(50f);
            this.mapView.Height = Dim.Percent(60f);
            this.mapView.X = 0;
            this.mapView.Y = 0;
            this.mapView.Data = "mapView";
            this.mapView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.mapView.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.mapView.Border.Effect3D = false;
            this.mapView.Border.Effect3DBrush = null;
            this.mapView.Border.DrawMarginFrame = true;
            this.mapView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.mapView.Title = "Map";
            this.Add(this.mapView);
            this.tableView.Width = Dim.Fill(0);
            this.tableView.Height = Dim.Fill(0);
            this.tableView.X = 1;
            this.tableView.Y = 0;
            this.tableView.Data = "tableView";
            this.tableView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.tableView.FullRowSelect = false;
            this.tableView.Style.AlwaysShowHeaders = false;
            this.tableView.Style.ExpandLastColumn = true;
            this.tableView.Style.InvertSelectedCellFirstCharacter = false;
            this.tableView.Style.ShowHorizontalHeaderOverline = true;
            this.tableView.Style.ShowHorizontalHeaderUnderline = true;
            this.tableView.Style.ShowVerticalCellLines = true;
            this.tableView.Style.ShowVerticalHeaderLines = true;
            System.Data.DataTable tableViewTable;
            tableViewTable = new System.Data.DataTable();
            System.Data.DataColumn tableViewTableA;
            tableViewTableA = new System.Data.DataColumn();
            tableViewTableA.ColumnName = "A";
            tableViewTable.Columns.Add(tableViewTableA);
            System.Data.DataColumn tableViewTableB;
            tableViewTableB = new System.Data.DataColumn();
            tableViewTableB.ColumnName = "B";
            tableViewTable.Columns.Add(tableViewTableB);
            System.Data.DataColumn tableViewTableC;
            tableViewTableC = new System.Data.DataColumn();
            tableViewTableC.ColumnName = "C";
            tableViewTable.Columns.Add(tableViewTableC);
            System.Data.DataColumn tableViewTableD;
            tableViewTableD = new System.Data.DataColumn();
            tableViewTableD.ColumnName = "D";
            tableViewTable.Columns.Add(tableViewTableD);
            System.Data.DataColumn tableViewTableE;
            tableViewTableE = new System.Data.DataColumn();
            tableViewTableE.ColumnName = "E";
            tableViewTable.Columns.Add(tableViewTableE);
            this.tableView.Table = tableViewTable;
            this.mapView.Add(this.tableView);
            this.tabView.Width = Dim.Fill(0);
            this.tabView.Height = Dim.Percent(60f);
            this.tabView.X = Pos.Percent(50f);
            this.tabView.Y = 0;
            this.tabView.Data = "tabView";
            this.tabView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.tabView.MaxTabTextWidth = 30u;
            this.tabView.Style.ShowBorder = true;
            this.tabView.Style.ShowTopLine = true;
            this.tabView.Style.TabsOnBottom = false;
            Terminal.Gui.TabView.Tab tabViewtileInfo;
            tabViewtileInfo = new Terminal.Gui.TabView.Tab("Tile Info", new View());
            tabViewtileInfo.View.Width = Dim.Fill();
            tabViewtileInfo.View.Height = Dim.Fill();
            tabView.AddTab(tabViewtileInfo, false);
            Terminal.Gui.TabView.Tab tabViewstats;
            tabViewstats = new Terminal.Gui.TabView.Tab("Stats", new View());
            tabViewstats.View.Width = Dim.Fill();
            tabViewstats.View.Height = Dim.Fill();
            tabView.AddTab(tabViewstats, false);
            Terminal.Gui.TabView.Tab tabVieweffects;
            tabVieweffects = new Terminal.Gui.TabView.Tab("Effects", new View());
            tabVieweffects.View.Width = Dim.Fill();
            tabVieweffects.View.Height = Dim.Fill();
            tabView.AddTab(tabVieweffects, false);
            Terminal.Gui.TabView.Tab tabViewresearch;
            tabViewresearch = new Terminal.Gui.TabView.Tab("Research", new View());
            tabViewresearch.View.Width = Dim.Fill();
            tabViewresearch.View.Height = Dim.Fill();
            tabView.AddTab(tabViewresearch, false);
            Terminal.Gui.TabView.Tab tabViewhelp;
            tabViewhelp = new Terminal.Gui.TabView.Tab("Help", new View());
            tabViewhelp.View.Width = Dim.Fill();
            tabViewhelp.View.Height = Dim.Fill();
            tabView.AddTab(tabViewhelp, false);
            this.tabView.ApplyStyleChanges();
            this.Add(this.tabView);
            this.frameView.Width = Dim.Percent(50f);
            this.frameView.Height = Dim.Fill(0);
            this.frameView.X = 0;
            this.frameView.Y = Pos.Percent(60f);
            this.frameView.Data = "frameView";
            this.frameView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.frameView.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.frameView.Border.Effect3D = false;
            this.frameView.Border.Effect3DBrush = null;
            this.frameView.Border.DrawMarginFrame = true;
            this.frameView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView.Title = "Hand";
            this.Add(this.frameView);
            this.frameView2.Width = Dim.Fill(0);
            this.frameView2.Height = Dim.Fill(0);
            this.frameView2.X = Pos.Percent(50f);
            this.frameView2.Y = Pos.Percent(60f);
            this.frameView2.Data = "frameView2";
            this.frameView2.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.frameView2.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.frameView2.Border.Effect3D = false;
            this.frameView2.Border.Effect3DBrush = null;
            this.frameView2.Border.DrawMarginFrame = true;
            this.frameView2.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.frameView2.Title = "Controlls";
            this.Add(this.frameView2);
        }
    }
}
