using Tiny4X.GameUtils.Map;

//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.23.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Tiny4X.UI.GameStage
{
    using Terminal.Gui;


    public partial class GameStage
    {

        public GameStage()
        {
            InitializeComponent();

            TurnOffTextFields();

            Map map = new Map();
            mapTable.Table = map.ConvertMapToTable();

            mapTable.SelectedCellChanged += ((e) =>
            {
                if (e.NewCol == 0) return;

                //Console.WriteLine($"selected: {e.NewRow}/{e.NewCol - 1}");
                tileInfoTextArea.Text = map.GetFieldInfo(e.NewCol - 1, e.NewRow);
            });

        }

        private void TurnOffTextFields()
        {
            tileInfoTextArea.Enabled = false;
            descriptionTextfield.Enabled = false;
            selectedCardEffectTextField.Enabled = false;
            researchDescriptionTextArea.Enabled = false;
            helpTextArea.Enabled = false;
            statsTextArea.Enabled = false;
            effectsTextArea.Enabled = false;
        }
    }
}
