
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.23.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Tiny4X.UI.GameStage {
    using System;
    using Terminal.Gui;
    
    
    public partial class GameStage : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme tgDefault;
        
        private Terminal.Gui.ColorScheme greyOnBlack;
        
        private Terminal.Gui.FrameView mapView;
        
        private Terminal.Gui.TableView mapTable;
        
        private Terminal.Gui.TabView infoView;
        
        private Terminal.Gui.TextView tileInfoTextArea;
        
        private Terminal.Gui.TextView statsTextArea;
        
        private Terminal.Gui.TextView effectsTextArea;
        
        private Terminal.Gui.FrameView reaserchableView;
        
        private Terminal.Gui.ListView researchableList;
        
        private Terminal.Gui.FrameView unlockedResearchView;
        
        private Terminal.Gui.ListView unlockedReaserchableList;
        
        private Terminal.Gui.FrameView allResearchView;
        
        private Terminal.Gui.ListView allResearchList;
        
        private Terminal.Gui.FrameView researchDescriptionView;
        
        private Terminal.Gui.TextView reserachDescriptionTextArea;
        
        private Terminal.Gui.FrameView topicView;
        
        private Terminal.Gui.ListView topicList;
        
        private Terminal.Gui.FrameView helpView;
        
        private Terminal.Gui.TextView helpTextArea;
        
        private Terminal.Gui.FrameView handView;
        
        private Terminal.Gui.FrameView handCardListView;
        
        private Terminal.Gui.FrameView descriptionView;
        
        private Terminal.Gui.TextView descriptionTextfield;
        
        private Terminal.Gui.FrameView selectedCardEffectView;
        
        private Terminal.Gui.TextView selectedCardeffectTextField;
        
        private Terminal.Gui.FrameView controllView;
        
        private Terminal.Gui.Button btnPlayCard;
        
        private void InitializeComponent() {
            this.btnPlayCard = new Terminal.Gui.Button();
            this.controllView = new Terminal.Gui.FrameView();
            this.selectedCardeffectTextField = new Terminal.Gui.TextView();
            this.selectedCardEffectView = new Terminal.Gui.FrameView();
            this.descriptionTextfield = new Terminal.Gui.TextView();
            this.descriptionView = new Terminal.Gui.FrameView();
            this.handCardListView = new Terminal.Gui.FrameView();
            this.handView = new Terminal.Gui.FrameView();
            this.helpTextArea = new Terminal.Gui.TextView();
            this.helpView = new Terminal.Gui.FrameView();
            this.topicList = new Terminal.Gui.ListView();
            this.topicView = new Terminal.Gui.FrameView();
            this.reserachDescriptionTextArea = new Terminal.Gui.TextView();
            this.researchDescriptionView = new Terminal.Gui.FrameView();
            this.allResearchList = new Terminal.Gui.ListView();
            this.allResearchView = new Terminal.Gui.FrameView();
            this.unlockedReaserchableList = new Terminal.Gui.ListView();
            this.unlockedResearchView = new Terminal.Gui.FrameView();
            this.researchableList = new Terminal.Gui.ListView();
            this.reaserchableView = new Terminal.Gui.FrameView();
            this.effectsTextArea = new Terminal.Gui.TextView();
            this.statsTextArea = new Terminal.Gui.TextView();
            this.tileInfoTextArea = new Terminal.Gui.TextView();
            this.infoView = new Terminal.Gui.TabView();
            this.mapTable = new Terminal.Gui.TableView();
            this.mapView = new Terminal.Gui.FrameView();
            this.tgDefault = new Terminal.Gui.ColorScheme();
            this.tgDefault.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.tgDefault.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightCyan, Terminal.Gui.Color.Blue);
            this.tgDefault.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.tgDefault.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Gray);
            this.tgDefault.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Brown, Terminal.Gui.Color.Blue);
            this.greyOnBlack = new Terminal.Gui.ColorScheme();
            this.greyOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 1;
            this.Y = 0;
            this.ColorScheme = this.greyOnBlack;
            this.Modal = true;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Double;
            this.Border.BorderBrush = Terminal.Gui.Color.Blue;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Tiny4X!";
            this.mapView.Width = Dim.Percent(50f);
            this.mapView.Height = Dim.Percent(60f);
            this.mapView.X = 0;
            this.mapView.Y = 0;
            this.mapView.Data = "mapView";
            this.mapView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.mapView.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.mapView.Border.Effect3D = false;
            this.mapView.Border.Effect3DBrush = null;
            this.mapView.Border.DrawMarginFrame = true;
            this.mapView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.mapView.Title = "Map";
            this.Add(this.mapView);
            this.mapTable.Width = Dim.Fill(0);
            this.mapTable.Height = Dim.Fill(0);
            this.mapTable.X = 0;
            this.mapTable.Y = 0;
            this.mapTable.Data = "mapTable";
            this.mapTable.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.mapTable.FullRowSelect = false;
            this.mapTable.Style.AlwaysShowHeaders = false;
            this.mapTable.Style.ExpandLastColumn = true;
            this.mapTable.Style.InvertSelectedCellFirstCharacter = false;
            this.mapTable.Style.ShowHorizontalHeaderOverline = true;
            this.mapTable.Style.ShowHorizontalHeaderUnderline = true;
            this.mapTable.Style.ShowVerticalCellLines = true;
            this.mapTable.Style.ShowVerticalHeaderLines = true;
            System.Data.DataTable mapTableTable;
            mapTableTable = new System.Data.DataTable();
            System.Data.DataColumn mapTableTableA;
            mapTableTableA = new System.Data.DataColumn();
            mapTableTableA.ColumnName = "A";
            mapTableTable.Columns.Add(mapTableTableA);
            System.Data.DataColumn mapTableTableB;
            mapTableTableB = new System.Data.DataColumn();
            mapTableTableB.ColumnName = "B";
            mapTableTable.Columns.Add(mapTableTableB);
            System.Data.DataColumn mapTableTableC;
            mapTableTableC = new System.Data.DataColumn();
            mapTableTableC.ColumnName = "C";
            mapTableTable.Columns.Add(mapTableTableC);
            System.Data.DataColumn mapTableTableD;
            mapTableTableD = new System.Data.DataColumn();
            mapTableTableD.ColumnName = "D";
            mapTableTable.Columns.Add(mapTableTableD);
            System.Data.DataColumn mapTableTableE;
            mapTableTableE = new System.Data.DataColumn();
            mapTableTableE.ColumnName = "E";
            mapTableTable.Columns.Add(mapTableTableE);
            this.mapTable.Table = mapTableTable;
            this.mapView.Add(this.mapTable);
            this.infoView.Width = Dim.Fill(0);
            this.infoView.Height = Dim.Percent(60f);
            this.infoView.X = Pos.Percent(50f);
            this.infoView.Y = 0;
            this.infoView.Data = "infoView";
            this.infoView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.infoView.MaxTabTextWidth = 30u;
            this.infoView.Style.ShowBorder = true;
            this.infoView.Style.ShowTopLine = true;
            this.infoView.Style.TabsOnBottom = false;
            Terminal.Gui.TabView.Tab infoViewtileInfo;
            infoViewtileInfo = new Terminal.Gui.TabView.Tab("Tile Info", new View());
            infoViewtileInfo.View.Width = Dim.Fill();
            infoViewtileInfo.View.Height = Dim.Fill();
            this.tileInfoTextArea.Width = Dim.Fill(0);
            this.tileInfoTextArea.Height = Dim.Fill(0);
            this.tileInfoTextArea.X = 1;
            this.tileInfoTextArea.Y = 0;
            this.tileInfoTextArea.AllowsTab = true;
            this.tileInfoTextArea.AllowsReturn = true;
            this.tileInfoTextArea.WordWrap = false;
            this.tileInfoTextArea.Data = "tileInfoTextArea";
            this.tileInfoTextArea.Text = "Example Text\r\n";
            this.tileInfoTextArea.TextAlignment = Terminal.Gui.TextAlignment.Left;
            infoViewtileInfo.View.Add(this.tileInfoTextArea);
            infoView.AddTab(infoViewtileInfo, false);
            Terminal.Gui.TabView.Tab infoViewstats;
            infoViewstats = new Terminal.Gui.TabView.Tab("Stats", new View());
            infoViewstats.View.Width = Dim.Fill();
            infoViewstats.View.Height = Dim.Fill();
            this.statsTextArea.Width = Dim.Fill(0);
            this.statsTextArea.Height = Dim.Fill(0);
            this.statsTextArea.X = 1;
            this.statsTextArea.Y = 0;
            this.statsTextArea.AllowsTab = true;
            this.statsTextArea.AllowsReturn = true;
            this.statsTextArea.WordWrap = false;
            this.statsTextArea.Data = "statsTextArea";
            this.statsTextArea.Text = "Example Text";
            this.statsTextArea.TextAlignment = Terminal.Gui.TextAlignment.Left;
            infoViewstats.View.Add(this.statsTextArea);
            infoView.AddTab(infoViewstats, false);
            Terminal.Gui.TabView.Tab infoVieweffects;
            infoVieweffects = new Terminal.Gui.TabView.Tab("Effects", new View());
            infoVieweffects.View.Width = Dim.Fill();
            infoVieweffects.View.Height = Dim.Fill();
            this.effectsTextArea.Width = Dim.Fill(0);
            this.effectsTextArea.Height = Dim.Fill(0);
            this.effectsTextArea.X = 1;
            this.effectsTextArea.Y = 0;
            this.effectsTextArea.AllowsTab = true;
            this.effectsTextArea.AllowsReturn = true;
            this.effectsTextArea.WordWrap = false;
            this.effectsTextArea.Data = "effectsTextArea";
            this.effectsTextArea.Text = "Example Text\r\n";
            this.effectsTextArea.TextAlignment = Terminal.Gui.TextAlignment.Left;
            infoVieweffects.View.Add(this.effectsTextArea);
            infoView.AddTab(infoVieweffects, false);
            Terminal.Gui.TabView.Tab infoViewresearch;
            infoViewresearch = new Terminal.Gui.TabView.Tab("Research", new View());
            infoViewresearch.View.Width = Dim.Fill();
            infoViewresearch.View.Height = Dim.Fill();
            this.reaserchableView.Width = Dim.Percent(30f);
            this.reaserchableView.Height = Dim.Percent(60f);
            this.reaserchableView.X = 0;
            this.reaserchableView.Y = 0;
            this.reaserchableView.Data = "reaserchableView";
            this.reaserchableView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.reaserchableView.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.reaserchableView.Border.Effect3D = false;
            this.reaserchableView.Border.Effect3DBrush = null;
            this.reaserchableView.Border.DrawMarginFrame = true;
            this.reaserchableView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.reaserchableView.Title = "Reaserchable";
            infoViewresearch.View.Add(this.reaserchableView);
            this.researchableList.Width = Dim.Fill(0);
            this.researchableList.Height = Dim.Fill(0);
            this.researchableList.X = 0;
            this.researchableList.Y = 0;
            this.researchableList.Data = "researchableList";
            this.researchableList.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.researchableList.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Item1",
                        "Item2",
                        "Item3"});
            this.reaserchableView.Add(this.researchableList);
            this.unlockedResearchView.Width = Dim.Percent(30f);
            this.unlockedResearchView.Height = Dim.Percent(60f);
            this.unlockedResearchView.X = Pos.Percent(30f);
            this.unlockedResearchView.Y = 0;
            this.unlockedResearchView.Data = "unlockedResearchView";
            this.unlockedResearchView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.unlockedResearchView.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.unlockedResearchView.Border.Effect3D = false;
            this.unlockedResearchView.Border.Effect3DBrush = null;
            this.unlockedResearchView.Border.DrawMarginFrame = true;
            this.unlockedResearchView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.unlockedResearchView.Title = "Unlocked";
            infoViewresearch.View.Add(this.unlockedResearchView);
            this.unlockedReaserchableList.Width = Dim.Fill(0);
            this.unlockedReaserchableList.Height = Dim.Fill(0);
            this.unlockedReaserchableList.X = 0;
            this.unlockedReaserchableList.Y = 0;
            this.unlockedReaserchableList.Data = "unlockedReaserchableList";
            this.unlockedReaserchableList.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.unlockedReaserchableList.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Item1",
                        "Item2",
                        "Item3"});
            this.unlockedResearchView.Add(this.unlockedReaserchableList);
            this.allResearchView.Width = Dim.Fill(0);
            this.allResearchView.Height = Dim.Percent(60f);
            this.allResearchView.X = Pos.Percent(60f);
            this.allResearchView.Y = 0;
            this.allResearchView.Data = "allResearchView";
            this.allResearchView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.allResearchView.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.allResearchView.Border.Effect3D = false;
            this.allResearchView.Border.Effect3DBrush = null;
            this.allResearchView.Border.DrawMarginFrame = true;
            this.allResearchView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.allResearchView.Title = "All";
            infoViewresearch.View.Add(this.allResearchView);
            this.allResearchList.Width = Dim.Fill(0);
            this.allResearchList.Height = Dim.Fill(0);
            this.allResearchList.X = 0;
            this.allResearchList.Y = 0;
            this.allResearchList.Data = "allResearchList";
            this.allResearchList.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.allResearchList.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Item1",
                        "Item2",
                        "Item3"});
            this.allResearchView.Add(this.allResearchList);
            this.researchDescriptionView.Width = Dim.Fill(0);
            this.researchDescriptionView.Height = Dim.Fill(0);
            this.researchDescriptionView.X = 0;
            this.researchDescriptionView.Y = Pos.Percent(60f);
            this.researchDescriptionView.Data = "researchDescriptionView";
            this.researchDescriptionView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.researchDescriptionView.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.researchDescriptionView.Border.Effect3D = false;
            this.researchDescriptionView.Border.Effect3DBrush = null;
            this.researchDescriptionView.Border.DrawMarginFrame = true;
            this.researchDescriptionView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.researchDescriptionView.Title = "Description";
            infoViewresearch.View.Add(this.researchDescriptionView);
            this.reserachDescriptionTextArea.Width = Dim.Fill(0);
            this.reserachDescriptionTextArea.Height = Dim.Fill(0);
            this.reserachDescriptionTextArea.X = 1;
            this.reserachDescriptionTextArea.Y = 0;
            this.reserachDescriptionTextArea.AllowsTab = true;
            this.reserachDescriptionTextArea.AllowsReturn = true;
            this.reserachDescriptionTextArea.WordWrap = false;
            this.reserachDescriptionTextArea.Data = "reserachDescriptionTextArea";
            this.reserachDescriptionTextArea.Text = "Example Text\r\n";
            this.reserachDescriptionTextArea.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.researchDescriptionView.Add(this.reserachDescriptionTextArea);
            infoView.AddTab(infoViewresearch, false);
            Terminal.Gui.TabView.Tab infoViewhelp;
            infoViewhelp = new Terminal.Gui.TabView.Tab("Help", new View());
            infoViewhelp.View.Width = Dim.Fill();
            infoViewhelp.View.Height = Dim.Fill();
            this.topicView.Width = Dim.Percent(30f);
            this.topicView.Height = Dim.Fill(0);
            this.topicView.X = 0;
            this.topicView.Y = 0;
            this.topicView.Data = "topicView";
            this.topicView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.topicView.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.topicView.Border.Effect3D = false;
            this.topicView.Border.Effect3DBrush = null;
            this.topicView.Border.DrawMarginFrame = true;
            this.topicView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.topicView.Title = "Topic";
            infoViewhelp.View.Add(this.topicView);
            this.topicList.Width = Dim.Fill(0);
            this.topicList.Height = Dim.Fill(0);
            this.topicList.X = 0;
            this.topicList.Y = 0;
            this.topicList.Data = "topicList";
            this.topicList.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.topicList.Source = new Terminal.Gui.ListWrapper(new string[] {
                        "Item1",
                        "Item2",
                        "Item3"});
            this.topicView.Add(this.topicList);
            this.helpView.Width = Dim.Fill(0);
            this.helpView.Height = Dim.Fill(0);
            this.helpView.X = Pos.Percent(30f);
            this.helpView.Y = 0;
            this.helpView.Data = "helpView";
            this.helpView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.helpView.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.helpView.Border.Effect3D = false;
            this.helpView.Border.Effect3DBrush = null;
            this.helpView.Border.DrawMarginFrame = true;
            this.helpView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.helpView.Title = "Info";
            infoViewhelp.View.Add(this.helpView);
            this.helpTextArea.Width = Dim.Fill(0);
            this.helpTextArea.Height = Dim.Fill(0);
            this.helpTextArea.X = 1;
            this.helpTextArea.Y = 0;
            this.helpTextArea.AllowsTab = true;
            this.helpTextArea.AllowsReturn = true;
            this.helpTextArea.WordWrap = false;
            this.helpTextArea.Data = "helpTextArea";
            this.helpTextArea.Text = "Example Text\r\n";
            this.helpTextArea.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.helpView.Add(this.helpTextArea);
            infoView.AddTab(infoViewhelp, false);
            this.infoView.ApplyStyleChanges();
            this.Add(this.infoView);
            this.handView.Width = Dim.Percent(50f);
            this.handView.Height = Dim.Fill(0);
            this.handView.X = 0;
            this.handView.Y = Pos.Percent(60f);
            this.handView.Data = "handView";
            this.handView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.handView.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.handView.Border.Effect3D = false;
            this.handView.Border.Effect3DBrush = null;
            this.handView.Border.DrawMarginFrame = true;
            this.handView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.handView.Title = "Hand";
            this.Add(this.handView);
            this.handCardListView.Width = Dim.Percent(40f);
            this.handCardListView.Height = Dim.Fill(0);
            this.handCardListView.X = 0;
            this.handCardListView.Y = 0;
            this.handCardListView.Data = "handCardListView";
            this.handCardListView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.handCardListView.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.handCardListView.Border.Effect3D = false;
            this.handCardListView.Border.Effect3DBrush = null;
            this.handCardListView.Border.DrawMarginFrame = true;
            this.handCardListView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.handCardListView.Title = "Cards";
            this.handView.Add(this.handCardListView);
            this.descriptionView.Width = Dim.Fill(0);
            this.descriptionView.Height = Dim.Percent(50f);
            this.descriptionView.X = Pos.Percent(40f);
            this.descriptionView.Y = 0;
            this.descriptionView.Data = "descriptionView";
            this.descriptionView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.descriptionView.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.descriptionView.Border.Effect3D = false;
            this.descriptionView.Border.Effect3DBrush = null;
            this.descriptionView.Border.DrawMarginFrame = true;
            this.descriptionView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.descriptionView.Title = "Description";
            this.handView.Add(this.descriptionView);
            this.descriptionTextfield.Width = Dim.Fill(0);
            this.descriptionTextfield.Height = Dim.Fill(0);
            this.descriptionTextfield.X = 1;
            this.descriptionTextfield.Y = 0;
            this.descriptionTextfield.AllowsTab = true;
            this.descriptionTextfield.AllowsReturn = true;
            this.descriptionTextfield.WordWrap = false;
            this.descriptionTextfield.Data = "descriptionTextfield";
            this.descriptionTextfield.Text = "Example Text";
            this.descriptionTextfield.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.descriptionView.Add(this.descriptionTextfield);
            this.selectedCardEffectView.Width = Dim.Fill(0);
            this.selectedCardEffectView.Height = Dim.Fill(0);
            this.selectedCardEffectView.X = Pos.Percent(40f);
            this.selectedCardEffectView.Y = Pos.Percent(50f);
            this.selectedCardEffectView.Data = "selectedCardEffectView";
            this.selectedCardEffectView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.selectedCardEffectView.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.selectedCardEffectView.Border.Effect3D = false;
            this.selectedCardEffectView.Border.Effect3DBrush = null;
            this.selectedCardEffectView.Border.DrawMarginFrame = true;
            this.selectedCardEffectView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.selectedCardEffectView.Title = "Selected Card Effects";
            this.handView.Add(this.selectedCardEffectView);
            this.selectedCardeffectTextField.Width = Dim.Fill(0);
            this.selectedCardeffectTextField.Height = Dim.Fill(0);
            this.selectedCardeffectTextField.X = 1;
            this.selectedCardeffectTextField.Y = 0;
            this.selectedCardeffectTextField.AllowsTab = true;
            this.selectedCardeffectTextField.AllowsReturn = true;
            this.selectedCardeffectTextField.WordWrap = false;
            this.selectedCardeffectTextField.Data = "selectedCardeffectTextField";
            this.selectedCardeffectTextField.Text = "Example Text\r\n";
            this.selectedCardeffectTextField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.selectedCardEffectView.Add(this.selectedCardeffectTextField);
            this.controllView.Width = Dim.Fill(0);
            this.controllView.Height = Dim.Fill(0);
            this.controllView.X = Pos.Percent(50f);
            this.controllView.Y = Pos.Percent(60f);
            this.controllView.Data = "controllView";
            this.controllView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.controllView.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.controllView.Border.Effect3D = false;
            this.controllView.Border.Effect3DBrush = null;
            this.controllView.Border.DrawMarginFrame = true;
            this.controllView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.controllView.Title = "Controlls";
            this.Add(this.controllView);
            this.btnPlayCard.Width = 10;
            this.btnPlayCard.Height = 1;
            this.btnPlayCard.X = Pos.Center();
            this.btnPlayCard.Y = Pos.Center();
            this.btnPlayCard.Data = "btnPlayCard";
            this.btnPlayCard.Text = "Play Card";
            this.btnPlayCard.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnPlayCard.IsDefault = false;
            this.controllView.Add(this.btnPlayCard);
        }
    }
}
