
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.23.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Tiny4X.UI.GameStage {
    using Terminal.Gui;
    
    
    public partial class GameStage {
        
        public GameStage() {
            InitializeComponent();
        }
    }
}
