using Terminal.Gui;
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.23.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Tiny4X.UI
{

    public partial class InputDialog : Terminal.Gui.Dialog
    {

        private Terminal.Gui.ColorScheme tgDefault;

        private Terminal.Gui.ColorScheme greyOnBlack;

        private Terminal.Gui.Label lbl;

        private Terminal.Gui.TextField textField;

        private Terminal.Gui.Button btnOk;

        private Terminal.Gui.Button btnCancel;

        private void InitializeComponent()
        {
            this.btnCancel = new Terminal.Gui.Button();
            this.btnOk = new Terminal.Gui.Button();
            this.textField = new Terminal.Gui.TextField();
            this.lbl = new Terminal.Gui.Label();
            this.tgDefault = new Terminal.Gui.ColorScheme();
            this.tgDefault.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Blue);
            this.tgDefault.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightCyan, Terminal.Gui.Color.Blue);
            this.tgDefault.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.Gray);
            this.tgDefault.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Gray);
            this.tgDefault.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Brown, Terminal.Gui.Color.Blue);
            this.greyOnBlack = new Terminal.Gui.ColorScheme();
            this.greyOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.Width = 20;
            this.Height = 6;
            this.X = 45;
            this.Y = 11;
            this.ColorScheme = this.greyOnBlack;
            this.Modal = true;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Double;
            this.Border.BorderBrush = Terminal.Gui.Color.Blue;
            this.Border.Effect3D = true;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Input";
            this.lbl.Width = 4;
            this.lbl.Height = 1;
            this.lbl.X = 1;
            this.lbl.Y = 0;
            this.lbl.ColorScheme = this.greyOnBlack;
            this.lbl.Data = "lbl";
            this.lbl.Text = "Input:";
            this.lbl.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.lbl);
            this.textField.Width = Dim.Fill(1);
            this.textField.Height = 1;
            this.textField.X = 8;
            this.textField.Y = 0;
            this.textField.Secret = false;
            this.textField.Data = "textField";
            this.textField.Text = "";
            this.textField.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.textField);
            this.btnOk.Width = 6;
            this.btnOk.Height = 1;
            this.btnOk.X = 1;
            this.btnOk.Y = 2;
            this.btnOk.Data = "btnOk";
            this.btnOk.Text = "Ok";
            this.btnOk.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnOk.IsDefault = false;
            this.Add(this.btnOk);
            this.btnCancel.Width = 10;
            this.btnCancel.Height = 1;
            this.btnCancel.X = 8;
            this.btnCancel.Y = 2;
            this.btnCancel.Data = "btnCancel";
            this.btnCancel.Text = "Cancel";
            this.btnCancel.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.btnCancel.IsDefault = false;
            this.Add(this.btnCancel);
        }
    }
}
