using Terminal.Gui;
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.23.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace Tiny4X.UI
{

    public partial class InputDialog : Dialog
    {

        public string? value { get; private set; }

        public InputDialog(string title, string label)
        {
            InitializeComponent();

            Title = title;
            lbl.Text = label;

            btnOk.IsDefault = true;

            btnCancel.Clicked += () => Application.RequestStop();
            btnOk.Clicked += () =>
            {
                value = (string)textField.Text;
                Application.RequestStop();
            };

            Console.WriteLine("in Diag");
        }
    }

}

